---

- hosts: server
  become: true
  gather_facts: no

  pre_tasks:

  - name: Retriving secrets
    include_vars: "secrets.yml"
    no_log: true

  - name: Pre-staging phase - including configuration variables
    include_vars:
      file: env.yml
    no_log: True

  - name: Checking services facts
    service_facts:
    
  - name: Check if Pipeline service is configured
    stat:
      path: "/etc/systemd/system/pipeline.service"
    register: pipeline_init

  tasks:

  - name: Stop Pipeline process ( doesn't stop Pipeline if manually launched)
    service:
      name: pipeline
      state: stopped
    when: pipeline_init.stat.exists == True

  - name: Stop service influxd, if started
    service:
      name: influxd
      state: stopped
    when: "'influxdb.service' in services"
 
  - name: Stop service grafana-server, if started
    service:
      name: grafana-server
      state: stopped
    when: "'grafana-server.service' in services"

  - name: Clean data directory
    file:
      state: absent
      path: "{{ data_path }}"

  - name: Clean log directory
    file:
      state: absent
      path: "{{ log_path }}"

 
  - name: Remove pipeline.service from systemd configuration (/etc/systemd/system)
    file:
      state: absent
      path: "/etc/systemd/system/pipeline.service"

  - name: Remove Influx consumer from pipeline.conf
    blockinfile:
      path: "{{env_path}}/pipeline.conf"
      state: absent
      marker: "#<!-- {mark} Ansible Managed  - Influx Config -->"
