---

- hosts: server
  become: true
  gather_facts: no

  pre_tasks:

  - name: Retriving secrets
    include_vars: "secrets.yml"
    no_log: true

  - name: Pre-staging phase - including configuration variables
    include_vars:
      file: env.yml
    no_log: True
    tags:
      - debug

  - name: Checking Pipeline process status
    service: 
      name: pipeline
      pattern: pipeline
      enabled: yes
    ignore_errors: True 
    register: pipeline_up

  tasks:

  - name: Update pipeline.conf for GRPC Dial-in 
    blockinfile:
      path: "{{env_path}}/pipeline.conf"
      marker: "#<!-- {mark} Ansible Managed  - GRPC Dial-In Config -->"
      block: "{{ lookup('file', 'templates/gRPCDialinnoTLS.cfg') }}"

  - name: Restart Pipeline (init) - if running
    service:
      name: pipeline
      state: restarted
    when: pipeline_up|succeeded

