---

- hosts: server
  become: true
  gather_facts: no

  pre_tasks:

  - name: Retriving secrets
    include_vars: "secrets.yml"
    no_log: true

  - name: Pre-staging phase - including configuration variables
    include_vars:
      file: env.yml
    no_log: True

  - name: Check if Pipeline service is configured
    stat:
      path: "/etc/systemd/system/pipeline.service"
    register: pipeline_init

  tasks:

  - name: Stop Pipeline process ( doesn't stop Pipeline if manually launched)
    service:
      name: pipeline
      state: stopped
    when: pipeline_init.stat.exists == True


  # Issue if stopped state:present and stopped:yes, start the docker-compose and and then stop
  # I want to stop only if it is already started (avoid creation of volumes data, log owned by root)
  # Volumes are own by root but I start docker-compose from normal user
  - name: Stop InfluxDB, and Grafana service
    service: 
      name: influxdb
      state: stopped

  - name: Check Grafana-server process status
    service: 
      name: grafana-server
      state: stopped