---

- hosts: server
  become: false
  gather_facts: no

  pre_tasks:

  - name: Retriving secrets
    include_vars: "secrets.yml"
    no_log: true

  - name: Pre-staging phase - including configuration variables
    include_vars:
      file: env.yml
    no_log: True


  tasks:

  #- name: test for blockinfile
  #  blockinfile:
  #    path: "{{env_path}}/pipeline.conf"
  #    #path: ~/environment/ansible/marco.conf
  #    #state: absent
  #    marker: "<!-- {mark} Ansible Managed  - Influx Config -->"
  #    block: "{{ lookup('file', 'templates/influx.cfg') }}"
  #    #block: "{{ lookup('file', 'influx.cfg') }}"
  #    #block: |
  #    #  <h1>Welcome to </h1>
  #    #  <p>Last updated on ansible</p>

  - name: Checking Pipeline process status
    service: 
      name: pipeline
      pattern: pipeline
      enabled: yes
    ignore_errors: True 
    register: pipeline_up

  - debug:
      msg: "{{ pipeline_up }}"
    when: pipeline_up|succeeded

  #- name: Confirm Automation Agent is running
  #  command: service mongodb-mms-automation-agent status
  #  register: agent_status
  #  failed_when: "'NOT' in agent_status.stdout"
  #  changed_when: False
